# Setup
title:               Netnesia
tagline:             'teknologi & kultur digital'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://netnesia.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Netnesia
  url:               https://twitter.com/netnesia
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
